spring :
  datasource :
    url : "jdbc:mysql://localhost:3306/ordercore"
    username : "root"
    password : "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari :
      minimumIdle : 0
      maximumPoolSize : 20
